apiVersion: v1
kind: PersistentVolume
metadata:
    name: jenkins-pv
spec:
    capacity:
        storage: 20Gi
    volumeMode: Filesystem
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    storageClassName: local-storage
    local:
        path: /data/jenkins
    nodeAffinity:
        required:
            nodeSelectorTerms:
                - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                            - 2001-b011-2007-3948-0215-5dff-fe01-6d01.dynamic-ip6.hinet.net 