apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: jenkins-pvc
spec:
    accessModes:
        - ReadWriteOnce
    storageClassName: local-storage
    resources:
        requests:
            storage: 20Gi
    volumeName: jenkins-pv